import type { EventConfig } from './types';

const event: EventConfig = {
  slug: 'data-center-summit',
  title: 'Data Center Summit 2026',
  titleHtml: 'DATA CENTER <br /> SUMMIT 2026',
  dateBadge: 'MAY 13-14, 2026 • NEW YORK CITY',
  tagline: 'Join industry leaders, developers, hyper scalers and investors as we define the next generation of synthetic infrastructure and high-frequency data ecosystems.',
  pageTitle: 'Data Center Summit 2026',
  ticketModalText: 'Choose which day you\'d like to attend.',
  ticketLinks: [
    { label: 'Day 1', sublabel: '— May 13, 2026', url: 'https://luma.com/l0inulj5' },
    { label: 'Day 2', sublabel: '— May 14, 2026', url: 'https://luma.com/9ouwc89o' },
  ],
  featuredSpeakers: [
    { name: 'Rajiv Bazaj', title: 'VP, Energy & Sustainability Solutions, Constellation', img: '/razi.png', pos: 'center 30%', linkedin: 'https://www.linkedin.com/in/rajiv-bazaj-b03225141/' },
    { name: 'Bill Thomas', title: 'Chief Energy Officer, CleanArc Data Centers', img: '/bill-thomas.png', pos: 'center 20%', linkedin: 'https://www.linkedin.com/in/bill-thomas-335a0843/' },
  ],
  speakers: [
    { name: 'Rajiv Bazaj', title: 'VP, Energy & Sustainability Solutions, Constellation', linkedin: 'https://www.linkedin.com/in/rajiv-bazaj-b03225141/' },
    { name: 'Bill Thomas', title: 'Chief Energy Officer, CleanArc Data Centers', linkedin: 'https://www.linkedin.com/in/bill-thomas-335a0843/' },
    { name: 'Matt Kittell', title: 'Senior Financial Specialist, Société Générale', linkedin: 'https://www.linkedin.com/in/matt-kittell-7582632/' },
    { name: 'Jim Costello', title: 'Head of Real Estate Economics, Chief Economist, MSCI Real Assets', linkedin: 'https://www.linkedin.com/in/jim-costello-9277174/' },
    { name: 'Sheila Oviedo', title: 'Head of Climate Risk Products, S&P', linkedin: 'https://www.linkedin.com/in/sheilaoviedo/' },
    { name: 'Radhika Mehrotra', title: 'Head of Data & Channel Partnerships, Americas, CDP', linkedin: 'https://www.linkedin.com/in/radhika-mehrotra-5a06819/' },
    { name: 'Peter Hoegler', title: 'Associate Director, EDF Power Solutions North America', linkedin: 'https://www.linkedin.com/in/peter-hoegler/' },
    { name: 'Kelsyn Rooks', title: 'Dir. of Strategic Accounts - AI Solutions, Cupix', linkedin: 'https://www.linkedin.com/in/kelsynrooks/' },
    { name: 'Jon M. Williams', title: 'Chairman & CEO, Viridi', linkedin: 'https://www.linkedin.com/in/jon-m-williams-1b741123a/' },
    { name: 'Ambroise Lalloz', title: 'AI & Energy, First Block', linkedin: 'https://www.linkedin.com/in/ambroise-l/' },
    { name: 'Malio West', title: 'Senior Partner, Global Accounting', linkedin: 'https://www.linkedin.com/in/dr-malio-west-pmp-cma-999a2712/' },
    { name: 'Aundre Oldacre', title: 'Co-Founder & Managing Partner, AoRa Development', linkedin: 'https://www.linkedin.com/in/aundreoldacre/' },
    { name: 'Dennis Garrett', title: 'CEO, Blue Lake Clean Energy Group', linkedin: 'https://www.linkedin.com/in/djgarrett/' },
    { name: 'Brian Weed', title: 'VP, Critical & Controlled Environment Services, GDI Integrated Facility Services', linkedin: 'https://www.linkedin.com/in/brianweed17/' },
    { name: 'Jay Peck', title: 'Principal, Brookhaven Sustainability', linkedin: 'https://www.linkedin.com/in/jay-peck-64459725/' },
    { name: 'Eric Bosworth', title: 'Principal, Thermal Energy Insights', linkedin: 'https://www.linkedin.com/in/ericbosworth/' },
    { name: 'Matthew Kaplan', title: 'VP of Project Development, Brightcore Energy', linkedin: 'https://www.linkedin.com/in/mattkaplan/' },
    { name: 'Esther Tierney', title: 'Senior Product Manager, Trane Technologies', linkedin: 'https://www.linkedin.com/in/esther-tierney-31b25959/' },
    { name: 'Fulya Kocak', title: 'CEO & Founder, Fulya Kocak, LLC', linkedin: 'https://www.linkedin.com/in/fulyakocak/' },
    { name: 'David Deutsch', title: 'COO, New Power Solutions', linkedin: 'https://www.linkedin.com/in/dedeutsch/' },
    { name: 'Hassan Saleh', title: 'CEO, VTV Energy', linkedin: 'https://www.linkedin.com/in/hassan-saleh-457a9a170/' },
    { name: 'Kelly Bacon', title: 'Principal, AECOM', linkedin: 'https://www.linkedin.com/in/kelly-bacon-a4220713/' },
    { name: 'Matt Short', title: 'Chief Commercial Officer, Paddle Energy', linkedin: 'https://www.linkedin.com/in/matt-short-6b26605/' },
    { name: 'David Sattler', title: 'CEO, SCDesign', linkedin: 'https://www.linkedin.com/in/david-sattler-6421918/' },
    { name: 'Larry Skennion', title: 'CEO, Green Panther Advisory', linkedin: 'https://www.linkedin.com/in/larry-skennion-ms-a410921/' },
    { name: 'Loren Burnett', title: 'CEO, Prometheus Materials', linkedin: 'https://www.linkedin.com/in/loren-burnett/' },
    { name: 'Kimberly Dowdell', title: 'VP Strategic Partnerships, Amrize', linkedin: 'https://www.linkedin.com/in/kimberlydowdell/' },
    { name: 'Hadia Sheerazi', title: 'Program Consultant, Mission Possible Partnership', linkedin: 'https://www.linkedin.com/in/hadiasheerazi/' },
    { name: 'Soumya Anantharaman', title: 'Director - Climate and Decarbonization, JLL', linkedin: 'https://www.linkedin.com/in/soumya-anantharaman-8b358831/' },
    { name: 'Chas Peppers', title: 'Director, SOM IW, Skidmore, Owings & Merrill', linkedin: 'https://www.linkedin.com/in/chas-peppers-3712365/' },
    { name: 'David Chernis', title: 'Director, Flexible Compute Platforms, CPower', linkedin: 'https://www.linkedin.com/in/davidchernis/' },
    { name: 'Nidhi Chadda', title: 'Founder & CEO, Enzo Advisors LLC', linkedin: 'https://www.linkedin.com/in/nchadda/' },
    { name: 'Matthew Carmody', title: 'Director of Digital Infrastructure, Voltus', linkedin: '' },
    { name: 'Brian Tormey', title: 'President, TitleVest', linkedin: '' },
    { name: 'Graeme Kavanagh', title: 'Partner and CRO, Accelerate Infrastructure Opportunities', linkedin: 'https://www.linkedin.com/in/gkavanagh/' },
    { name: 'Alexander Jahn', title: 'Innovation Advisor, NYSERDA', linkedin: '' },
    { name: 'Martin Renkis', title: 'Executive Director, Data Center Infrastructure, Johnson Controls', linkedin: 'https://www.linkedin.com/in/martinrenkis/' },
    { name: 'Ruben Petit', title: 'CCO, Ener.co', linkedin: 'https://www.linkedin.com/in/ruben-petit-589316b9/' },
    { name: 'Michael (Mick) Gilbert, PE, CEM', title: 'Board Member, Decarb Summits', linkedin: 'https://www.linkedin.com/in/michaelhgilbert/' },
    { name: 'Will Pettitt', title: 'Global Geothermal Lead, Baker Hughes', linkedin: '' },
    { name: 'Scott Donachie', title: 'CEO, Decarb Summits', linkedin: 'https://www.linkedin.com/in/scott-donachie-5683787/' },
  ],
  schedule: [
    {
      label: 'Day 1',
      date: 'May 13, 2026',
      subtitle: 'Data Center Investing and Planning',
      sessions: [
        { time: '8:00–8:50 AM', title: 'Registration & Networking', type: 'break' },
        { time: '8:50–9:00 AM', title: 'Opening Remarks', speakers: ['Chas Peppers, Director, SOM IW, Skidmore, Owings & Merrill'] },
        { time: '9:00–9:40 AM', title: 'Data Center Investing & Strategic Planning: From Permitting to Full Operations', speakers: ['Hadia Sheerazi, Program Consultant, Mission Possible Partnership', 'Kelly Bacon, Principal, AECOM', 'Bill Thomas, Chief Energy Officer, CleanArc Data Centers', 'Matt Short, Chief Commercial Officer, Paddle Energy'] },
        { time: '9:40–10:00 AM', title: 'AI Factories as Virtual Power Plants: Bridging the Grid Capacity Gap', speakers: ['David Chernis, Director, Flexible Compute Platforms at CPower'] },
        { time: '10:00–10:30 AM', title: 'Balancing Data Center Expansion: Addressing Equipment Reliability and Energy Efficiency', speakers: ['Soumya Anantharaman (Moderator), Director - Climate and Decarbonization, JLL', 'Brian Weed, VP, Critical & Controlled Environment Services, GDI Integrated Facility Services'] },
        { time: '10:30–11:00 AM', title: 'Coffee & Networking', type: 'break' },
        { time: '11:00–11:30 AM', title: 'Building the Future: AI in Data Center Construction', speakers: ['Martin Renkis (Moderator), Executive Director, Data Center Infrastructure, Johnson Controls', 'Aundre Oldacre, Co-Founder & Managing Partner, AoRa Development', 'Kelsyn Rooks, Dir. of Strategic Accounts - AI Solutions, Cupix'] },
        { time: '11:30 AM–12:00 PM', title: 'Decarbonization Opportunities for Legacy Data Centers: Optimizing Existing Cooling Infrastructure', speakers: ['David Sattler, CEO, SCDesign', 'Ruben Petit, CCO, Ener.co'] },
        { time: '12:00–12:45 PM', title: 'Lunch & Networking', type: 'break' },
        { time: '12:45–1:15 PM', title: 'The Importance of Hyperlocal Data Collection to Assess Water Risk for Data Centers', speakers: ['Nidhi Chadda (Moderator), Founder & CEO, Enzo Advisors LLC', 'Sheila Oviedo, Head of Climate Risk Products, S&P', 'Radhika Mehrotra, Head of Data & Channel Partnerships, Americas, CDP'] },
        { time: '1:15–1:35 PM', title: 'Scaling Low-Carbon Material Technology and Collaborating with Hyperscalers to Reduce Embodied Carbon in Large-Scale Infrastructure Projects', speakers: ['Loren Burnett, CEO, Prometheus Materials'] },
        { time: '1:35–1:55 PM', title: 'How Data-Driven Material Optimization Can Reduce Emissions in Construction', subtitle: 'Amrize and their collaboration with Meta, highlighting how AI was used to optimize low embodied carbon concrete design and deployment.', speakers: ['Kimberly Dowdell, VP Strategic Partnerships, Amrize'] },
        { time: '1:55–2:15 PM', title: 'Nuclear and Data Center Convergence: How Société Générale Sees Partnerships, Financing Structures, and Risk Mitigation Shaping Bankable, Large-Scale Deployments', speakers: ['Matt Kittell, Senior Financial Specialist, Société Générale'] },
        { time: '2:15–2:35 PM', title: 'Land, Leasing, and Real Estate Models', speakers: ['Jim Costello, Head of Real Estate Economics, Chief Economist, MSCI Real Assets'] },
        { time: '2:35 PM', title: 'Closing Remarks', type: 'closing' },
      ],
    },
    {
      label: 'Day 2',
      date: 'May 14, 2026',
      subtitle: 'Powering Data Centers & Grid Expansion — Onsite Power Generation',
      sessions: [
        { time: '8:00–9:00 AM', title: 'Registration & Networking with Breakfast', type: 'break' },
        { time: '9:00–9:30 AM', title: 'Opening Remarks: Balancing Affordability & Reliability', speakers: ['Rajiv Bazaj, Vice President, Energy & Sustainability Solutions, Constellation'] },
        { time: '9:30–10:00 AM', title: 'Hybrid Energy Systems: The Importance for Data Center Expansion', speakers: ['Michael (Mick) Gilbert, PE, CEM (Moderator), Board Member, Decarb Summits', 'Peter Hoegler, Associate Director, EDF Power Solutions North America', 'Hassan Saleh, CEO, VTV Energy'] },
        { time: '10:00–10:30 AM', title: 'Coffee & Networking', type: 'break' },
        { time: '10:30–11:00 AM', title: 'Battery Energy Storage Systems (BESS) Solutions', subtitle: 'Peak shaving, resiliency, and fast-response grid support', speakers: ['Jon M. Williams, Chairman & CEO, Viridi'] },
        { time: '11:00–11:30 AM', title: 'Bring Your Own Capacity for Data Centers', speakers: ['Scott Donachie (Moderator), CEO, Decarb Summits', 'Matthew Carmody, Director of Digital Infrastructure, Voltus'] },
        { time: '11:30–11:50 AM', title: 'Fireside Chat: Onsite Power Generation Turnkey Solutions — Power Plant as a Service', speakers: ['David Deutsch, COO, New Power Solutions', 'Scott Donachie (Moderator), CEO, Decarb Summits'] },
        { time: '11:50 AM–12:20 PM', title: 'Unique Capital Strategies: Exploring Proven Methods of Preserving or Recycling Capital While Retaining Site Control', speakers: ['Larry Skennion (Moderator), CEO, Green Panther Advisory', 'Brian Tormey, President, TitleVest', 'Graeme Kavanagh, Partner and CRO, Accelerate Infrastructure Opportunities'] },
        { time: '12:20–1:00 PM', title: 'Lunch & Networking', type: 'break' },
        { time: '1:00–2:00 PM', title: 'Waste Heat Recovery & Geothermal Solutions', subtitle: 'Capturing, repurposing, and monetizing data center thermal output.', speakers: ['Eric Bosworth (Moderator), Principal, Thermal Energy Insights', 'Matthew Kaplan, VP of Project Development, Brightcore Energy', 'Ambroise Lalloz, AI & Energy, First Block', 'Alexander Jahn, Innovation Advisor, NYSERDA', 'Will Pettitt, Global Geothermal Lead, Baker Hughes', 'Esther Tierney, Senior Product Manager, Trane Technologies'] },
        { time: '2:00–2:40 PM', title: 'Behind-the-Meter Data Center Solutions & Microgrids', subtitle: 'Hyperscale data center solutions cannot get the capacity from utility companies and must embrace new grid tech', speakers: ['Fulya Kocak (Moderator), CEO & Founder, Fulya Kocak LLC', 'Malio West, Senior Partner, Global Accounting', 'Dennis Garrett, CEO, Blue Lake Clean Energy Group', 'Jay Peck, Principal, Brookhaven Sustainability'] },
        { time: '2:40 PM', title: 'Closing Remarks', speakers: ['Scott Donachie, CEO, Decarb Summits'], type: 'closing' },
      ],
    },
  ],
  whyAttend: [
    'Gain exclusive access to roadmap reveals for next-generation cooling and power systems.',
    'Network with the elite 1% of data center engineers and sustainability officers.',
    'Direct Q&A sessions with regulatory bodies shaping the future of industrial data usage.',
  ],
  whoShouldAttend: ['Investors', 'Land Developers', 'Data Center Developers', 'Hyper Scalers', 'AI Pioneers', 'Onsite Power Providers'],
  partners: [
    { name: 'Constellation Energy', url: 'https://www.constellationenergy.com' },
    { name: 'NYSERDA', url: 'https://www.nyserda.ny.gov' },
    { name: 'Trane Technologies', url: 'https://www.tranetechnologies.com' },
    { name: 'Brightcore', url: 'https://www.brightcoreenergy.com' },
    { name: 'Voltus', url: 'https://www.voltus.co' },
    { name: 'CPower', url: 'https://cpowerenergy.com' },
    { name: 'Ainsworth GDI', url: 'https://www.gdi.com' },
    { name: 'Green Panther Advisory Services', url: 'https://www.greenpantheradvisory.com' },
  ],
  signupDescription: 'Sign up for updates on the Data Center Summit 2026 and future Decarb Summits events.',
  email: {
    fromName: 'Data Center Summit',
    notificationHeading: 'New Interest Sign-Up — Data Center Summit 2026',
    welcomeTitle: 'Welcome to Data Center Summit 2026',
    welcomeSubject: "You're on the list — Data Center Summit 2026",
    welcomeBody: 'the <strong style="color:#ffffff;">Data Center Summit 2026</strong> — the premier gathering for industry leaders, developers, hyper scalers, and investors shaping the future of sustainable data infrastructure.',
    eventBoxName: 'Data Center Summit 2026',
    eventBoxDate: 'May 13–14, 2026 &nbsp;•&nbsp; New York City',
    ticketUrl: 'https://luma.com/l0inulj5',
  },
};

export default event;
